# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accountDetailsUiPb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='accountDetailsUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x61\x63\x63ountDetailsUiPb.proto\"\x95\x01\n\x12\x41\x63\x63ountDetailsUiPb\x12\x11\n\taccountNo\x18\x01 \x01(\t\x12\x10\n\x08ifscCode\x18\x02 \x01(\t\x12\x15\n\rrecipientName\x18\x03 \x01(\t\x12\x10\n\x08\x62\x61nkName\x18\x04 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x05 \x01(\t\x12!\n\tgooglePay\x18\x06 \x01(\x0b\x32\x0e.GooglePayUiPb\"\x1e\n\rGooglePayUiPb\x12\r\n\x05upiId\x18\x01 \x01(\t*M\n\x12\x41\x63\x63ountUseTypeEnum\x12\x18\n\x14UNKNOWN_ACCOUNT_TYPE\x10\x00\x12\x0e\n\nSINGLE_USE\x10\x01\x12\r\n\tMULTI_USE\x10\x02\x62\x06proto3'
)

_ACCOUNTUSETYPEENUM = _descriptor.EnumDescriptor(
  name='AccountUseTypeEnum',
  full_name='AccountUseTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ACCOUNT_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SINGLE_USE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MULTI_USE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=212,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTUSETYPEENUM)

AccountUseTypeEnum = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTUSETYPEENUM)
UNKNOWN_ACCOUNT_TYPE = 0
SINGLE_USE = 1
MULTI_USE = 2



_ACCOUNTDETAILSUIPB = _descriptor.Descriptor(
  name='AccountDetailsUiPb',
  full_name='AccountDetailsUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountNo', full_name='AccountDetailsUiPb.accountNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ifscCode', full_name='AccountDetailsUiPb.ifscCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recipientName', full_name='AccountDetailsUiPb.recipientName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bankName', full_name='AccountDetailsUiPb.bankName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branch', full_name='AccountDetailsUiPb.branch', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='googlePay', full_name='AccountDetailsUiPb.googlePay', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=178,
)


_GOOGLEPAYUIPB = _descriptor.Descriptor(
  name='GooglePayUiPb',
  full_name='GooglePayUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='upiId', full_name='GooglePayUiPb.upiId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=210,
)

_ACCOUNTDETAILSUIPB.fields_by_name['googlePay'].message_type = _GOOGLEPAYUIPB
DESCRIPTOR.message_types_by_name['AccountDetailsUiPb'] = _ACCOUNTDETAILSUIPB
DESCRIPTOR.message_types_by_name['GooglePayUiPb'] = _GOOGLEPAYUIPB
DESCRIPTOR.enum_types_by_name['AccountUseTypeEnum'] = _ACCOUNTUSETYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountDetailsUiPb = _reflection.GeneratedProtocolMessageType('AccountDetailsUiPb', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTDETAILSUIPB,
  '__module__' : 'accountDetailsUiPb_pb2'
  # @@protoc_insertion_point(class_scope:AccountDetailsUiPb)
  })
_sym_db.RegisterMessage(AccountDetailsUiPb)

GooglePayUiPb = _reflection.GeneratedProtocolMessageType('GooglePayUiPb', (_message.Message,), {
  'DESCRIPTOR' : _GOOGLEPAYUIPB,
  '__module__' : 'accountDetailsUiPb_pb2'
  # @@protoc_insertion_point(class_scope:GooglePayUiPb)
  })
_sym_db.RegisterMessage(GooglePayUiPb)


# @@protoc_insertion_point(module_scope)
