# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attendancePb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityPb_pb2 as entityPb__pb2
import namePb_pb2 as namePb__pb2
import timePb_pb2 as timePb__pb2
import classPb_pb2 as classPb__pb2
import attendanceUiPb_pb2 as attendanceUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='attendancePb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x61ttendancePb.proto\x1a\x0e\x65ntityPb.proto\x1a\x0cnamePb.proto\x1a\x0ctimePb.proto\x1a\rclassPb.proto\x1a\x14\x61ttendanceUiPb.proto\"\xc8\x01\n\x0c\x41ttendancePb\x12\x19\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\t.EntityPb\x12\x12\n\nattendeeId\x18\x02 \x01(\t\x12\x1d\n\x0c\x61ttendeeName\x18\x03 \x01(\x0b\x32\x07.NamePb\x12\x1c\n\x0b\x63reatedTime\x18\x04 \x01(\x0b\x32\x07.TimePb\x12-\n\x10\x61ttendanceStatus\x18\x05 \x01(\x0e\x32\x13.AttendanceTypeEnum\x12\x1d\n\x08\x63lassRef\x18\x06 \x01(\x0b\x32\x0b.ClassPbRefb\x06proto3'
  ,
  dependencies=[entityPb__pb2.DESCRIPTOR,namePb__pb2.DESCRIPTOR,timePb__pb2.DESCRIPTOR,classPb__pb2.DESCRIPTOR,attendanceUiPb__pb2.DESCRIPTOR,])




_ATTENDANCEPB = _descriptor.Descriptor(
  name='AttendancePb',
  full_name='AttendancePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='AttendancePb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendeeId', full_name='AttendancePb.attendeeId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendeeName', full_name='AttendancePb.attendeeName', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='AttendancePb.createdTime', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendanceStatus', full_name='AttendancePb.attendanceStatus', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classRef', full_name='AttendancePb.classRef', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=304,
)

_ATTENDANCEPB.fields_by_name['dbInfo'].message_type = entityPb__pb2._ENTITYPB
_ATTENDANCEPB.fields_by_name['attendeeName'].message_type = namePb__pb2._NAMEPB
_ATTENDANCEPB.fields_by_name['createdTime'].message_type = timePb__pb2._TIMEPB
_ATTENDANCEPB.fields_by_name['attendanceStatus'].enum_type = attendanceUiPb__pb2._ATTENDANCETYPEENUM
_ATTENDANCEPB.fields_by_name['classRef'].message_type = classPb__pb2._CLASSPBREF
DESCRIPTOR.message_types_by_name['AttendancePb'] = _ATTENDANCEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttendancePb = _reflection.GeneratedProtocolMessageType('AttendancePb', (_message.Message,), {
  'DESCRIPTOR' : _ATTENDANCEPB,
  '__module__' : 'attendancePb_pb2'
  # @@protoc_insertion_point(class_scope:AttendancePb)
  })
_sym_db.RegisterMessage(AttendancePb)


# @@protoc_insertion_point(module_scope)
