# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attendanceUiPb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityUiPb_pb2 as entityUiPb__pb2
import nameUiPb_pb2 as nameUiPb__pb2
import timeUiPb_pb2 as timeUiPb__pb2
import classUiPb_pb2 as classUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='attendanceUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x61ttendanceUiPb.proto\x1a\x10\x65ntityUiPb.proto\x1a\x0enameUiPb.proto\x1a\x0etimeUiPb.proto\x1a\x0f\x63lassUiPb.proto\"\xd2\x01\n\x0e\x41ttendanceUiPb\x12\x1b\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x0b.EntityUiPb\x12\x12\n\nattendeeId\x18\x02 \x01(\t\x12\x1f\n\x0c\x61ttendeeName\x18\x03 \x01(\x0b\x32\t.NameUiPb\x12\x1e\n\x0b\x63reatedTime\x18\x04 \x01(\x0b\x32\t.TimeUiPb\x12-\n\x10\x61ttendanceStatus\x18\x05 \x01(\x0e\x32\x13.AttendanceTypeEnum\x12\x1f\n\x08\x63lassRef\x18\x06 \x01(\x0b\x32\r.ClassUiPbRef*?\n\x12\x41ttendanceTypeEnum\x12\x13\n\x0f\x41TTENDEE_ABSENT\x10\x00\x12\x14\n\x10\x41TTENDEE_PRESENT\x10\x01\x62\x06proto3'
  ,
  dependencies=[entityUiPb__pb2.DESCRIPTOR,nameUiPb__pb2.DESCRIPTOR,timeUiPb__pb2.DESCRIPTOR,classUiPb__pb2.DESCRIPTOR,])

_ATTENDANCETYPEENUM = _descriptor.EnumDescriptor(
  name='AttendanceTypeEnum',
  full_name='AttendanceTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ATTENDEE_ABSENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTENDEE_PRESENT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=304,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_ATTENDANCETYPEENUM)

AttendanceTypeEnum = enum_type_wrapper.EnumTypeWrapper(_ATTENDANCETYPEENUM)
ATTENDEE_ABSENT = 0
ATTENDEE_PRESENT = 1



_ATTENDANCEUIPB = _descriptor.Descriptor(
  name='AttendanceUiPb',
  full_name='AttendanceUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='AttendanceUiPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendeeId', full_name='AttendanceUiPb.attendeeId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendeeName', full_name='AttendanceUiPb.attendeeName', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='AttendanceUiPb.createdTime', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attendanceStatus', full_name='AttendanceUiPb.attendanceStatus', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classRef', full_name='AttendanceUiPb.classRef', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=302,
)

_ATTENDANCEUIPB.fields_by_name['dbInfo'].message_type = entityUiPb__pb2._ENTITYUIPB
_ATTENDANCEUIPB.fields_by_name['attendeeName'].message_type = nameUiPb__pb2._NAMEUIPB
_ATTENDANCEUIPB.fields_by_name['createdTime'].message_type = timeUiPb__pb2._TIMEUIPB
_ATTENDANCEUIPB.fields_by_name['attendanceStatus'].enum_type = _ATTENDANCETYPEENUM
_ATTENDANCEUIPB.fields_by_name['classRef'].message_type = classUiPb__pb2._CLASSUIPBREF
DESCRIPTOR.message_types_by_name['AttendanceUiPb'] = _ATTENDANCEUIPB
DESCRIPTOR.enum_types_by_name['AttendanceTypeEnum'] = _ATTENDANCETYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttendanceUiPb = _reflection.GeneratedProtocolMessageType('AttendanceUiPb', (_message.Message,), {
  'DESCRIPTOR' : _ATTENDANCEUIPB,
  '__module__' : 'attendanceUiPb_pb2'
  # @@protoc_insertion_point(class_scope:AttendanceUiPb)
  })
_sym_db.RegisterMessage(AttendanceUiPb)


# @@protoc_insertion_point(module_scope)
