# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityUiPb_pb2 as entityUiPb__pb2
import nameUiPb_pb2 as nameUiPb__pb2
import timeUiPb_pb2 as timeUiPb__pb2
import classTypeUiPb_pb2 as classTypeUiPb__pb2
import schoolUiPb_pb2 as schoolUiPb__pb2
import sectionUiPb_pb2 as sectionUiPb__pb2
import summaryUiPb_pb2 as summaryUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='classUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x63lassUiPb.proto\x1a\x10\x65ntityUiPb.proto\x1a\x0enameUiPb.proto\x1a\x0etimeUiPb.proto\x1a\x13\x63lassTypeUiPb.proto\x1a\x10schoolUiPb.proto\x1a\x11sectionUiPb.proto\x1a\x11summaryUiPb.proto\"\xe1\x01\n\tClassUiPb\x12\x1b\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x0b.EntityUiPb\x12\x17\n\x04name\x18\x02 \x01(\x0b\x32\t.NameUiPb\x12!\n\tclassType\x18\x03 \x01(\x0e\x32\x0e.ClassTypeEnum\x12%\n\x0bsectionType\x18\x04 \x01(\x0e\x32\x10.SectionTypeEnum\x12!\n\tschoolRef\x18\x05 \x01(\x0b\x32\x0e.SchoolUiPbRef\x12\x11\n\tclassCode\x18\x06 \x01(\t\x12\x1e\n\x0b\x63reatedTime\x18\x07 \x01(\x0b\x32\t.TimeUiPb\"\x9a\x01\n\x0c\x43lassUiPbRef\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\tschoolRef\x18\x02 \x01(\x0b\x32\x0e.SchoolUiPbRef\x12\x11\n\tclassCode\x18\x03 \x01(\t\x12!\n\tclassType\x18\x04 \x01(\x0e\x32\x0e.ClassTypeEnum\x12%\n\x0bsectionType\x18\x05 \x01(\x0e\x32\x10.SectionTypeEnum\"\x18\n\x16\x43lassSearchRequestUiPb\"U\n\x17\x43lassSearchResponseUiPb\x12\x1d\n\x07summary\x18\x01 \x01(\x0b\x32\x0c.SummaryUiPb\x12\x1b\n\x07results\x18\x02 \x03(\x0b\x32\n.ClassUiPbb\x06proto3'
  ,
  dependencies=[entityUiPb__pb2.DESCRIPTOR,nameUiPb__pb2.DESCRIPTOR,timeUiPb__pb2.DESCRIPTOR,classTypeUiPb__pb2.DESCRIPTOR,schoolUiPb__pb2.DESCRIPTOR,sectionUiPb__pb2.DESCRIPTOR,summaryUiPb__pb2.DESCRIPTOR,])




_CLASSUIPB = _descriptor.Descriptor(
  name='ClassUiPb',
  full_name='ClassUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='ClassUiPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ClassUiPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classType', full_name='ClassUiPb.classType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionType', full_name='ClassUiPb.sectionType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolRef', full_name='ClassUiPb.schoolRef', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classCode', full_name='ClassUiPb.classCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='ClassUiPb.createdTime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=372,
)


_CLASSUIPBREF = _descriptor.Descriptor(
  name='ClassUiPbRef',
  full_name='ClassUiPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ClassUiPbRef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolRef', full_name='ClassUiPbRef.schoolRef', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classCode', full_name='ClassUiPbRef.classCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classType', full_name='ClassUiPbRef.classType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionType', full_name='ClassUiPbRef.sectionType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=529,
)


_CLASSSEARCHREQUESTUIPB = _descriptor.Descriptor(
  name='ClassSearchRequestUiPb',
  full_name='ClassSearchRequestUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=555,
)


_CLASSSEARCHRESPONSEUIPB = _descriptor.Descriptor(
  name='ClassSearchResponseUiPb',
  full_name='ClassSearchResponseUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='ClassSearchResponseUiPb.summary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='ClassSearchResponseUiPb.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=642,
)

_CLASSUIPB.fields_by_name['dbInfo'].message_type = entityUiPb__pb2._ENTITYUIPB
_CLASSUIPB.fields_by_name['name'].message_type = nameUiPb__pb2._NAMEUIPB
_CLASSUIPB.fields_by_name['classType'].enum_type = classTypeUiPb__pb2._CLASSTYPEENUM
_CLASSUIPB.fields_by_name['sectionType'].enum_type = sectionUiPb__pb2._SECTIONTYPEENUM
_CLASSUIPB.fields_by_name['schoolRef'].message_type = schoolUiPb__pb2._SCHOOLUIPBREF
_CLASSUIPB.fields_by_name['createdTime'].message_type = timeUiPb__pb2._TIMEUIPB
_CLASSUIPBREF.fields_by_name['schoolRef'].message_type = schoolUiPb__pb2._SCHOOLUIPBREF
_CLASSUIPBREF.fields_by_name['classType'].enum_type = classTypeUiPb__pb2._CLASSTYPEENUM
_CLASSUIPBREF.fields_by_name['sectionType'].enum_type = sectionUiPb__pb2._SECTIONTYPEENUM
_CLASSSEARCHRESPONSEUIPB.fields_by_name['summary'].message_type = summaryUiPb__pb2._SUMMARYUIPB
_CLASSSEARCHRESPONSEUIPB.fields_by_name['results'].message_type = _CLASSUIPB
DESCRIPTOR.message_types_by_name['ClassUiPb'] = _CLASSUIPB
DESCRIPTOR.message_types_by_name['ClassUiPbRef'] = _CLASSUIPBREF
DESCRIPTOR.message_types_by_name['ClassSearchRequestUiPb'] = _CLASSSEARCHREQUESTUIPB
DESCRIPTOR.message_types_by_name['ClassSearchResponseUiPb'] = _CLASSSEARCHRESPONSEUIPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassUiPb = _reflection.GeneratedProtocolMessageType('ClassUiPb', (_message.Message,), {
  'DESCRIPTOR' : _CLASSUIPB,
  '__module__' : 'classUiPb_pb2'
  # @@protoc_insertion_point(class_scope:ClassUiPb)
  })
_sym_db.RegisterMessage(ClassUiPb)

ClassUiPbRef = _reflection.GeneratedProtocolMessageType('ClassUiPbRef', (_message.Message,), {
  'DESCRIPTOR' : _CLASSUIPBREF,
  '__module__' : 'classUiPb_pb2'
  # @@protoc_insertion_point(class_scope:ClassUiPbRef)
  })
_sym_db.RegisterMessage(ClassUiPbRef)

ClassSearchRequestUiPb = _reflection.GeneratedProtocolMessageType('ClassSearchRequestUiPb', (_message.Message,), {
  'DESCRIPTOR' : _CLASSSEARCHREQUESTUIPB,
  '__module__' : 'classUiPb_pb2'
  # @@protoc_insertion_point(class_scope:ClassSearchRequestUiPb)
  })
_sym_db.RegisterMessage(ClassSearchRequestUiPb)

ClassSearchResponseUiPb = _reflection.GeneratedProtocolMessageType('ClassSearchResponseUiPb', (_message.Message,), {
  'DESCRIPTOR' : _CLASSSEARCHRESPONSEUIPB,
  '__module__' : 'classUiPb_pb2'
  # @@protoc_insertion_point(class_scope:ClassSearchResponseUiPb)
  })
_sym_db.RegisterMessage(ClassSearchResponseUiPb)


# @@protoc_insertion_point(module_scope)
