# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deviceInfoUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityUiPb_pb2 as entityUiPb__pb2
import timeUiPb_pb2 as timeUiPb__pb2
import genericRefUiPb_pb2 as genericRefUiPb__pb2
import userTypeUiPb_pb2 as userTypeUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deviceInfoUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x64\x65viceInfoUiPb.proto\x1a\x10\x65ntityUiPb.proto\x1a\x0etimeUiPb.proto\x1a\x14genericRefUiPb.proto\x1a\x12userTypeUiPb.proto\"\xdf\x01\n\x0e\x44\x65viceInfoUiPb\x12\x1b\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x0b.EntityUiPb\x12\x10\n\x08macAddId\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0e\n\x06osType\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x1e\n\x0b\x63reatedTime\x18\x07 \x01(\x0b\x32\t.TimeUiPb\x12\x1d\n\x04user\x18\x08 \x01(\x0b\x32\x0f.GenericRefUiPb\x12\x1f\n\x08userType\x18\t \x01(\x0e\x32\r.UserTypeEnumb\x06proto3'
  ,
  dependencies=[entityUiPb__pb2.DESCRIPTOR,timeUiPb__pb2.DESCRIPTOR,genericRefUiPb__pb2.DESCRIPTOR,userTypeUiPb__pb2.DESCRIPTOR,])




_DEVICEINFOUIPB = _descriptor.Descriptor(
  name='DeviceInfoUiPb',
  full_name='DeviceInfoUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='DeviceInfoUiPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='macAddId', full_name='DeviceInfoUiPb.macAddId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='DeviceInfoUiPb.deviceId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='DeviceInfoUiPb.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osType', full_name='DeviceInfoUiPb.osType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='DeviceInfoUiPb.state', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='DeviceInfoUiPb.createdTime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='DeviceInfoUiPb.user', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userType', full_name='DeviceInfoUiPb.userType', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=324,
)

_DEVICEINFOUIPB.fields_by_name['dbInfo'].message_type = entityUiPb__pb2._ENTITYUIPB
_DEVICEINFOUIPB.fields_by_name['createdTime'].message_type = timeUiPb__pb2._TIMEUIPB
_DEVICEINFOUIPB.fields_by_name['user'].message_type = genericRefUiPb__pb2._GENERICREFUIPB
_DEVICEINFOUIPB.fields_by_name['userType'].enum_type = userTypeUiPb__pb2._USERTYPEENUM
DESCRIPTOR.message_types_by_name['DeviceInfoUiPb'] = _DEVICEINFOUIPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceInfoUiPb = _reflection.GeneratedProtocolMessageType('DeviceInfoUiPb', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFOUIPB,
  '__module__' : 'deviceInfoUiPb_pb2'
  # @@protoc_insertion_point(class_scope:DeviceInfoUiPb)
  })
_sym_db.RegisterMessage(DeviceInfoUiPb)


# @@protoc_insertion_point(module_scope)
