# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emailUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='emailUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x65mailUiPb.proto\".\n\tEmailUiPb\x12\x11\n\tlocalPart\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tb\x06proto3'
)




_EMAILUIPB = _descriptor.Descriptor(
  name='EmailUiPb',
  full_name='EmailUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localPart', full_name='EmailUiPb.localPart', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='EmailUiPb.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['EmailUiPb'] = _EMAILUIPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailUiPb = _reflection.GeneratedProtocolMessageType('EmailUiPb', (_message.Message,), {
  'DESCRIPTOR' : _EMAILUIPB,
  '__module__' : 'emailUiPb_pb2'
  # @@protoc_insertion_point(class_scope:EmailUiPb)
  })
_sym_db.RegisterMessage(EmailUiPb)


# @@protoc_insertion_point(module_scope)
