# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errorTypeUiPb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='errorTypeUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x65rrorTypeUiPb.proto\"M\n\tErrorUiPb\x12!\n\terrorType\x18\x01 \x01(\x0e\x32\x0e.ErrorTypeEnum\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05*\xa7\x01\n\rErrorTypeEnum\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x0f\n\x0bINPUT_ERROR\x10\x01\x12\x1a\n\x16INPUT_VALIDATION_ERROR\x10\x02\x12\x0e\n\nJSON_ERROR\x10\x03\x12\x19\n\x15JSON_VALIDATION_ERROR\x10\x04\x12\x15\n\x11UN_EXPECTED_ERROR\x10\x05\x12\x14\n\x10INVALID_RESPONSE\x10\x06\x62\x06proto3'
)

_ERRORTYPEENUM = _descriptor.EnumDescriptor(
  name='ErrorTypeEnum',
  full_name='ErrorTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPUT_ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPUT_VALIDATION_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JSON_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JSON_VALIDATION_ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UN_EXPECTED_ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_RESPONSE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=103,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_ERRORTYPEENUM)

ErrorTypeEnum = enum_type_wrapper.EnumTypeWrapper(_ERRORTYPEENUM)
UNKNOWN_ERROR = 0
INPUT_ERROR = 1
INPUT_VALIDATION_ERROR = 2
JSON_ERROR = 3
JSON_VALIDATION_ERROR = 4
UN_EXPECTED_ERROR = 5
INVALID_RESPONSE = 6



_ERRORUIPB = _descriptor.Descriptor(
  name='ErrorUiPb',
  full_name='ErrorUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorType', full_name='ErrorUiPb.errorType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='ErrorUiPb.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='ErrorUiPb.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=100,
)

_ERRORUIPB.fields_by_name['errorType'].enum_type = _ERRORTYPEENUM
DESCRIPTOR.message_types_by_name['ErrorUiPb'] = _ERRORUIPB
DESCRIPTOR.enum_types_by_name['ErrorTypeEnum'] = _ERRORTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorUiPb = _reflection.GeneratedProtocolMessageType('ErrorUiPb', (_message.Message,), {
  'DESCRIPTOR' : _ERRORUIPB,
  '__module__' : 'errorTypeUiPb_pb2'
  # @@protoc_insertion_point(class_scope:ErrorUiPb)
  })
_sym_db.RegisterMessage(ErrorUiPb)


# @@protoc_insertion_point(module_scope)
