# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityUiPb_pb2 as entityUiPb__pb2
import emailUiPb_pb2 as emailUiPb__pb2
import genericRefUiPb_pb2 as genericRefUiPb__pb2
import userTypeUiPb_pb2 as userTypeUiPb__pb2
import timeUiPb_pb2 as timeUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loginUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0floginUiPb.proto\x1a\x10\x65ntityUiPb.proto\x1a\x0f\x65mailUiPb.proto\x1a\x14genericRefUiPb.proto\x1a\x12userTypeUiPb.proto\x1a\x0etimeUiPb.proto\"\xb8\x01\n\tLoginUiPb\x12\x1b\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x0b.EntityUiPb\x12\x19\n\x05\x65mail\x18\x02 \x01(\x0b\x32\n.EmailUiPb\x12\x10\n\x08password\x18\x03 \x01(\t\x12 \n\x07userRef\x18\x04 \x01(\x0b\x32\x0f.GenericRefUiPb\x12\x1f\n\x08userType\x18\x05 \x01(\x0e\x32\r.UserTypeEnum\x12\x1e\n\x0b\x63reatedTime\x18\x06 \x01(\x0b\x32\t.TimeUiPbb\x06proto3'
  ,
  dependencies=[entityUiPb__pb2.DESCRIPTOR,emailUiPb__pb2.DESCRIPTOR,genericRefUiPb__pb2.DESCRIPTOR,userTypeUiPb__pb2.DESCRIPTOR,timeUiPb__pb2.DESCRIPTOR,])




_LOGINUIPB = _descriptor.Descriptor(
  name='LoginUiPb',
  full_name='LoginUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='LoginUiPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='LoginUiPb.email', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginUiPb.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userRef', full_name='LoginUiPb.userRef', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userType', full_name='LoginUiPb.userType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='LoginUiPb.createdTime', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=297,
)

_LOGINUIPB.fields_by_name['dbInfo'].message_type = entityUiPb__pb2._ENTITYUIPB
_LOGINUIPB.fields_by_name['email'].message_type = emailUiPb__pb2._EMAILUIPB
_LOGINUIPB.fields_by_name['userRef'].message_type = genericRefUiPb__pb2._GENERICREFUIPB
_LOGINUIPB.fields_by_name['userType'].enum_type = userTypeUiPb__pb2._USERTYPEENUM
_LOGINUIPB.fields_by_name['createdTime'].message_type = timeUiPb__pb2._TIMEUIPB
DESCRIPTOR.message_types_by_name['LoginUiPb'] = _LOGINUIPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginUiPb = _reflection.GeneratedProtocolMessageType('LoginUiPb', (_message.Message,), {
  'DESCRIPTOR' : _LOGINUIPB,
  '__module__' : 'loginUiPb_pb2'
  # @@protoc_insertion_point(class_scope:LoginUiPb)
  })
_sym_db.RegisterMessage(LoginUiPb)


# @@protoc_insertion_point(module_scope)
