# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loginPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityPb_pb2 as entityPb__pb2
import emailPb_pb2 as emailPb__pb2
import genericRefPb_pb2 as genericRefPb__pb2
import userTypeUiPb_pb2 as userTypeUiPb__pb2
import timePb_pb2 as timePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='loginPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rloginPb.proto\x1a\x0e\x65ntityPb.proto\x1a\remailPb.proto\x1a\x12genericRefPb.proto\x1a\x12userTypeUiPb.proto\x1a\x0ctimePb.proto\"\xae\x01\n\x07LoginPb\x12\x19\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\t.EntityPb\x12\x17\n\x05\x65mail\x18\x02 \x01(\x0b\x32\x08.EmailPb\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x1e\n\x07userRef\x18\x04 \x01(\x0b\x32\r.GenericRefPb\x12\x1f\n\x08userType\x18\x05 \x01(\x0e\x32\r.UserTypeEnum\x12\x1c\n\x0b\x63reatedTime\x18\x06 \x01(\x0b\x32\x07.TimePbb\x06proto3'
  ,
  dependencies=[entityPb__pb2.DESCRIPTOR,emailPb__pb2.DESCRIPTOR,genericRefPb__pb2.DESCRIPTOR,userTypeUiPb__pb2.DESCRIPTOR,timePb__pb2.DESCRIPTOR,])




_LOGINPB = _descriptor.Descriptor(
  name='LoginPb',
  full_name='LoginPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='LoginPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='LoginPb.email', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginPb.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userRef', full_name='LoginPb.userRef', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userType', full_name='LoginPb.userType', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='LoginPb.createdTime', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=277,
)

_LOGINPB.fields_by_name['dbInfo'].message_type = entityPb__pb2._ENTITYPB
_LOGINPB.fields_by_name['email'].message_type = emailPb__pb2._EMAILPB
_LOGINPB.fields_by_name['userRef'].message_type = genericRefPb__pb2._GENERICREFPB
_LOGINPB.fields_by_name['userType'].enum_type = userTypeUiPb__pb2._USERTYPEENUM
_LOGINPB.fields_by_name['createdTime'].message_type = timePb__pb2._TIMEPB
DESCRIPTOR.message_types_by_name['LoginPb'] = _LOGINPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginPb = _reflection.GeneratedProtocolMessageType('LoginPb', (_message.Message,), {
  'DESCRIPTOR' : _LOGINPB,
  '__module__' : 'loginPb_pb2'
  # @@protoc_insertion_point(class_scope:LoginPb)
  })
_sym_db.RegisterMessage(LoginPb)


# @@protoc_insertion_point(module_scope)
