# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nameUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nameUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0enameUiPb.proto\"Z\n\x08NameUiPb\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x12\n\nmiddleName\x18\x02 \x03(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\x15\n\rcanonicalName\x18\x04 \x01(\tb\x06proto3'
)




_NAMEUIPB = _descriptor.Descriptor(
  name='NameUiPb',
  full_name='NameUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='NameUiPb.firstName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middleName', full_name='NameUiPb.middleName', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='NameUiPb.lastName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canonicalName', full_name='NameUiPb.canonicalName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['NameUiPb'] = _NAMEUIPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameUiPb = _reflection.GeneratedProtocolMessageType('NameUiPb', (_message.Message,), {
  'DESCRIPTOR' : _NAMEUIPB,
  '__module__' : 'nameUiPb_pb2'
  # @@protoc_insertion_point(class_scope:NameUiPb)
  })
_sym_db.RegisterMessage(NameUiPb)


# @@protoc_insertion_point(module_scope)
