# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organisationPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import namePb_pb2 as namePb__pb2
import entityPb_pb2 as entityPb__pb2
import timePb_pb2 as timePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='organisationPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14organisationPb.proto\x1a\x0cnamePb.proto\x1a\x0e\x65ntityPb.proto\x1a\x0ctimePb.proto\"j\n\x0eOrganisationPb\x12\x19\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\t.EntityPb\x12\x15\n\x04name\x18\x02 \x01(\x0b\x32\x07.NamePb\x12\x15\n\x04time\x18\x03 \x01(\x0b\x32\x07.TimePb\x12\x0f\n\x07orgCode\x18\x04 \x01(\tb\x06proto3'
  ,
  dependencies=[namePb__pb2.DESCRIPTOR,entityPb__pb2.DESCRIPTOR,timePb__pb2.DESCRIPTOR,])




_ORGANISATIONPB = _descriptor.Descriptor(
  name='OrganisationPb',
  full_name='OrganisationPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='OrganisationPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='OrganisationPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='OrganisationPb.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orgCode', full_name='OrganisationPb.orgCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=174,
)

_ORGANISATIONPB.fields_by_name['dbInfo'].message_type = entityPb__pb2._ENTITYPB
_ORGANISATIONPB.fields_by_name['name'].message_type = namePb__pb2._NAMEPB
_ORGANISATIONPB.fields_by_name['time'].message_type = timePb__pb2._TIMEPB
DESCRIPTOR.message_types_by_name['OrganisationPb'] = _ORGANISATIONPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrganisationPb = _reflection.GeneratedProtocolMessageType('OrganisationPb', (_message.Message,), {
  'DESCRIPTOR' : _ORGANISATIONPB,
  '__module__' : 'organisationPb_pb2'
  # @@protoc_insertion_point(class_scope:OrganisationPb)
  })
_sym_db.RegisterMessage(OrganisationPb)


# @@protoc_insertion_point(module_scope)
