# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schoolPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityPb_pb2 as entityPb__pb2
import namePb_pb2 as namePb__pb2
import addressPb_pb2 as addressPb__pb2
import timePb_pb2 as timePb__pb2
import mobilePb_pb2 as mobilePb__pb2
import classTypeUiPb_pb2 as classTypeUiPb__pb2
import sectionUiPb_pb2 as sectionUiPb__pb2
import genericRefPb_pb2 as genericRefPb__pb2
import accountDetailsPb_pb2 as accountDetailsPb__pb2
import accountDetailsUiPb_pb2 as accountDetailsUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='schoolPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0eschoolPb.proto\x1a\x0e\x65ntityPb.proto\x1a\x0cnamePb.proto\x1a\x0f\x61\x64\x64ressPb.proto\x1a\x0ctimePb.proto\x1a\x0emobilePb.proto\x1a\x13\x63lassTypeUiPb.proto\x1a\x11sectionUiPb.proto\x1a\x12genericRefPb.proto\x1a\x16\x61\x63\x63ountDetailsPb.proto\x1a\x18\x61\x63\x63ountDetailsUiPb.proto\"\xed\x02\n\x08SchoolPb\x12\x19\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\t.EntityPb\x12\x15\n\x04name\x18\x02 \x01(\x0b\x32\x07.NamePb\x12\x1b\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\n.AddressPb\x12\x19\n\x06mobile\x18\x04 \x03(\x0b\x32\t.MobilePb\x12\x1c\n\x0b\x63reatedTime\x18\x05 \x01(\x0b\x32\x07.TimePb\x12#\n\x0corganisation\x18\x06 \x01(\x0b\x32\r.GenericRefPb\x12\x12\n\nschoolCode\x18\x07 \x01(\t\x12+\n\x0e\x61\x63\x63ountUseType\x18\x08 \x01(\x0e\x32\x13.AccountUseTypeEnum\x12)\n\x0e\x61\x63\x63ountDetails\x18\t \x01(\x0b\x32\x11.AccountDetailsPb\x12!\n\tclassType\x18\n \x03(\x0e\x32\x0e.ClassTypeEnum\x12%\n\x0bsectionType\x18\x0b \x03(\x0e\x32\x10.SectionTypeEnum\"\x9c\x01\n\x0bSchoolPbRef\x12\n\n\x02id\x18\x01 \x01(\t\x12#\n\x0corganisation\x18\x02 \x01(\x0b\x32\r.GenericRefPb\x12\x12\n\nschoolCode\x18\x03 \x01(\t\x12!\n\tclassType\x18\n \x03(\x0e\x32\x0e.ClassTypeEnum\x12%\n\x0bsectionType\x18\x0b \x03(\x0e\x32\x10.SectionTypeEnumb\x06proto3'
  ,
  dependencies=[entityPb__pb2.DESCRIPTOR,namePb__pb2.DESCRIPTOR,addressPb__pb2.DESCRIPTOR,timePb__pb2.DESCRIPTOR,mobilePb__pb2.DESCRIPTOR,classTypeUiPb__pb2.DESCRIPTOR,sectionUiPb__pb2.DESCRIPTOR,genericRefPb__pb2.DESCRIPTOR,accountDetailsPb__pb2.DESCRIPTOR,accountDetailsUiPb__pb2.DESCRIPTOR,])




_SCHOOLPB = _descriptor.Descriptor(
  name='SchoolPb',
  full_name='SchoolPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='SchoolPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='SchoolPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='SchoolPb.address', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='SchoolPb.mobile', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='SchoolPb.createdTime', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organisation', full_name='SchoolPb.organisation', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolCode', full_name='SchoolPb.schoolCode', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accountUseType', full_name='SchoolPb.accountUseType', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accountDetails', full_name='SchoolPb.accountDetails', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classType', full_name='SchoolPb.classType', index=9,
      number=10, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionType', full_name='SchoolPb.sectionType', index=10,
      number=11, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=571,
)


_SCHOOLPBREF = _descriptor.Descriptor(
  name='SchoolPbRef',
  full_name='SchoolPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SchoolPbRef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organisation', full_name='SchoolPbRef.organisation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolCode', full_name='SchoolPbRef.schoolCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classType', full_name='SchoolPbRef.classType', index=3,
      number=10, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sectionType', full_name='SchoolPbRef.sectionType', index=4,
      number=11, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=730,
)

_SCHOOLPB.fields_by_name['dbInfo'].message_type = entityPb__pb2._ENTITYPB
_SCHOOLPB.fields_by_name['name'].message_type = namePb__pb2._NAMEPB
_SCHOOLPB.fields_by_name['address'].message_type = addressPb__pb2._ADDRESSPB
_SCHOOLPB.fields_by_name['mobile'].message_type = mobilePb__pb2._MOBILEPB
_SCHOOLPB.fields_by_name['createdTime'].message_type = timePb__pb2._TIMEPB
_SCHOOLPB.fields_by_name['organisation'].message_type = genericRefPb__pb2._GENERICREFPB
_SCHOOLPB.fields_by_name['accountUseType'].enum_type = accountDetailsUiPb__pb2._ACCOUNTUSETYPEENUM
_SCHOOLPB.fields_by_name['accountDetails'].message_type = accountDetailsPb__pb2._ACCOUNTDETAILSPB
_SCHOOLPB.fields_by_name['classType'].enum_type = classTypeUiPb__pb2._CLASSTYPEENUM
_SCHOOLPB.fields_by_name['sectionType'].enum_type = sectionUiPb__pb2._SECTIONTYPEENUM
_SCHOOLPBREF.fields_by_name['organisation'].message_type = genericRefPb__pb2._GENERICREFPB
_SCHOOLPBREF.fields_by_name['classType'].enum_type = classTypeUiPb__pb2._CLASSTYPEENUM
_SCHOOLPBREF.fields_by_name['sectionType'].enum_type = sectionUiPb__pb2._SECTIONTYPEENUM
DESCRIPTOR.message_types_by_name['SchoolPb'] = _SCHOOLPB
DESCRIPTOR.message_types_by_name['SchoolPbRef'] = _SCHOOLPBREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchoolPb = _reflection.GeneratedProtocolMessageType('SchoolPb', (_message.Message,), {
  'DESCRIPTOR' : _SCHOOLPB,
  '__module__' : 'schoolPb_pb2'
  # @@protoc_insertion_point(class_scope:SchoolPb)
  })
_sym_db.RegisterMessage(SchoolPb)

SchoolPbRef = _reflection.GeneratedProtocolMessageType('SchoolPbRef', (_message.Message,), {
  'DESCRIPTOR' : _SCHOOLPBREF,
  '__module__' : 'schoolPb_pb2'
  # @@protoc_insertion_point(class_scope:SchoolPbRef)
  })
_sym_db.RegisterMessage(SchoolPbRef)


# @@protoc_insertion_point(module_scope)
