# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sectionUiPb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sectionUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11sectionUiPb.proto*q\n\x0fSectionTypeEnum\x12\x13\n\x0fUNKNOWN_SECTION\x10\x00\x12\r\n\tSECTION_A\x10\x01\x12\r\n\tSECTION_B\x10\x02\x12\r\n\tSECTION_C\x10\x03\x12\r\n\tSECTION_D\x10\x04\x12\r\n\tSECTION_E\x10\x05\x62\x06proto3'
)

_SECTIONTYPEENUM = _descriptor.EnumDescriptor(
  name='SectionTypeEnum',
  full_name='SectionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SECTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_A', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_B', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_C', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_D', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SECTION_E', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=21,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_SECTIONTYPEENUM)

SectionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_SECTIONTYPEENUM)
UNKNOWN_SECTION = 0
SECTION_A = 1
SECTION_B = 2
SECTION_C = 3
SECTION_D = 4
SECTION_E = 5


DESCRIPTOR.enum_types_by_name['SectionTypeEnum'] = _SECTIONTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
