# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teacherPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityPb_pb2 as entityPb__pb2
import namePb_pb2 as namePb__pb2
import mobilePb_pb2 as mobilePb__pb2
import emailPb_pb2 as emailPb__pb2
import schoolPb_pb2 as schoolPb__pb2
import timePb_pb2 as timePb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teacherPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fteacherPb.proto\x1a\x0e\x65ntityPb.proto\x1a\x0cnamePb.proto\x1a\x0emobilePb.proto\x1a\remailPb.proto\x1a\x0eschoolPb.proto\x1a\x0ctimePb.proto\"\xc5\x01\n\tTeacherPb\x12\x19\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\t.EntityPb\x12\x15\n\x04name\x18\x02 \x01(\x0b\x32\x07.NamePb\x12\x19\n\x06mobile\x18\x03 \x01(\x0b\x32\t.MobilePb\x12\x17\n\x05\x65mail\x18\x04 \x01(\x0b\x32\x08.EmailPb\x12\x1f\n\tschoolRef\x18\x05 \x01(\x0b\x32\x0c.SchoolPbRef\x12\x13\n\x0bteacherCode\x18\x06 \x01(\t\x12\x1c\n\x0b\x63reatedTime\x18\x07 \x01(\x0b\x32\x07.TimePb\"F\n\x0cTeacherPbRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\x04name\x18\x02 \x01(\x0b\x32\x07.NamePb\x12\x13\n\x0bteacherCode\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[entityPb__pb2.DESCRIPTOR,namePb__pb2.DESCRIPTOR,mobilePb__pb2.DESCRIPTOR,emailPb__pb2.DESCRIPTOR,schoolPb__pb2.DESCRIPTOR,timePb__pb2.DESCRIPTOR,])




_TEACHERPB = _descriptor.Descriptor(
  name='TeacherPb',
  full_name='TeacherPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='TeacherPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TeacherPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='TeacherPb.mobile', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='TeacherPb.email', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolRef', full_name='TeacherPb.schoolRef', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherCode', full_name='TeacherPb.teacherCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='TeacherPb.createdTime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=308,
)


_TEACHERPBREF = _descriptor.Descriptor(
  name='TeacherPbRef',
  full_name='TeacherPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TeacherPbRef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TeacherPbRef.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherCode', full_name='TeacherPbRef.teacherCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=380,
)

_TEACHERPB.fields_by_name['dbInfo'].message_type = entityPb__pb2._ENTITYPB
_TEACHERPB.fields_by_name['name'].message_type = namePb__pb2._NAMEPB
_TEACHERPB.fields_by_name['mobile'].message_type = mobilePb__pb2._MOBILEPB
_TEACHERPB.fields_by_name['email'].message_type = emailPb__pb2._EMAILPB
_TEACHERPB.fields_by_name['schoolRef'].message_type = schoolPb__pb2._SCHOOLPBREF
_TEACHERPB.fields_by_name['createdTime'].message_type = timePb__pb2._TIMEPB
_TEACHERPBREF.fields_by_name['name'].message_type = namePb__pb2._NAMEPB
DESCRIPTOR.message_types_by_name['TeacherPb'] = _TEACHERPB
DESCRIPTOR.message_types_by_name['TeacherPbRef'] = _TEACHERPBREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeacherPb = _reflection.GeneratedProtocolMessageType('TeacherPb', (_message.Message,), {
  'DESCRIPTOR' : _TEACHERPB,
  '__module__' : 'teacherPb_pb2'
  # @@protoc_insertion_point(class_scope:TeacherPb)
  })
_sym_db.RegisterMessage(TeacherPb)

TeacherPbRef = _reflection.GeneratedProtocolMessageType('TeacherPbRef', (_message.Message,), {
  'DESCRIPTOR' : _TEACHERPBREF,
  '__module__' : 'teacherPb_pb2'
  # @@protoc_insertion_point(class_scope:TeacherPbRef)
  })
_sym_db.RegisterMessage(TeacherPbRef)


# @@protoc_insertion_point(module_scope)
