# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teacherUiPb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entityUiPb_pb2 as entityUiPb__pb2
import nameUiPb_pb2 as nameUiPb__pb2
import mobileUiPb_pb2 as mobileUiPb__pb2
import emailUiPb_pb2 as emailUiPb__pb2
import schoolUiPb_pb2 as schoolUiPb__pb2
import timeUiPb_pb2 as timeUiPb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teacherUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11teacherUiPb.proto\x1a\x10\x65ntityUiPb.proto\x1a\x0enameUiPb.proto\x1a\x10mobileUiPb.proto\x1a\x0f\x65mailUiPb.proto\x1a\x10schoolUiPb.proto\x1a\x0etimeUiPb.proto\"\xd3\x01\n\x0bTeacherUiPb\x12\x1b\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x0b.EntityUiPb\x12\x17\n\x04name\x18\x02 \x01(\x0b\x32\t.NameUiPb\x12\x1b\n\x06mobile\x18\x03 \x01(\x0b\x32\x0b.MobileUiPb\x12\x19\n\x05\x65mail\x18\x04 \x01(\x0b\x32\n.EmailUiPb\x12!\n\tschoolRef\x18\x05 \x01(\x0b\x32\x0e.SchoolUiPbRef\x12\x13\n\x0bteacherCode\x18\x06 \x01(\t\x12\x1e\n\x0b\x63reatedTime\x18\x07 \x01(\x0b\x32\t.TimeUiPb\"J\n\x0eTeacherUiPbRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x04name\x18\x02 \x01(\x0b\x32\t.NameUiPb\x12\x13\n\x0bteacherCode\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[entityUiPb__pb2.DESCRIPTOR,nameUiPb__pb2.DESCRIPTOR,mobileUiPb__pb2.DESCRIPTOR,emailUiPb__pb2.DESCRIPTOR,schoolUiPb__pb2.DESCRIPTOR,timeUiPb__pb2.DESCRIPTOR,])




_TEACHERUIPB = _descriptor.Descriptor(
  name='TeacherUiPb',
  full_name='TeacherUiPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='TeacherUiPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TeacherUiPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='TeacherUiPb.mobile', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='TeacherUiPb.email', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schoolRef', full_name='TeacherUiPb.schoolRef', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherCode', full_name='TeacherUiPb.teacherCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='TeacherUiPb.createdTime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=336,
)


_TEACHERUIPBREF = _descriptor.Descriptor(
  name='TeacherUiPbRef',
  full_name='TeacherUiPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TeacherUiPbRef.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TeacherUiPbRef.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teacherCode', full_name='TeacherUiPbRef.teacherCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=412,
)

_TEACHERUIPB.fields_by_name['dbInfo'].message_type = entityUiPb__pb2._ENTITYUIPB
_TEACHERUIPB.fields_by_name['name'].message_type = nameUiPb__pb2._NAMEUIPB
_TEACHERUIPB.fields_by_name['mobile'].message_type = mobileUiPb__pb2._MOBILEUIPB
_TEACHERUIPB.fields_by_name['email'].message_type = emailUiPb__pb2._EMAILUIPB
_TEACHERUIPB.fields_by_name['schoolRef'].message_type = schoolUiPb__pb2._SCHOOLUIPBREF
_TEACHERUIPB.fields_by_name['createdTime'].message_type = timeUiPb__pb2._TIMEUIPB
_TEACHERUIPBREF.fields_by_name['name'].message_type = nameUiPb__pb2._NAMEUIPB
DESCRIPTOR.message_types_by_name['TeacherUiPb'] = _TEACHERUIPB
DESCRIPTOR.message_types_by_name['TeacherUiPbRef'] = _TEACHERUIPBREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeacherUiPb = _reflection.GeneratedProtocolMessageType('TeacherUiPb', (_message.Message,), {
  'DESCRIPTOR' : _TEACHERUIPB,
  '__module__' : 'teacherUiPb_pb2'
  # @@protoc_insertion_point(class_scope:TeacherUiPb)
  })
_sym_db.RegisterMessage(TeacherUiPb)

TeacherUiPbRef = _reflection.GeneratedProtocolMessageType('TeacherUiPbRef', (_message.Message,), {
  'DESCRIPTOR' : _TEACHERUIPBREF,
  '__module__' : 'teacherUiPb_pb2'
  # @@protoc_insertion_point(class_scope:TeacherUiPbRef)
  })
_sym_db.RegisterMessage(TeacherUiPbRef)


# @@protoc_insertion_point(module_scope)
