# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userTypeUiPb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userTypeUiPb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12userTypeUiPb.proto*[\n\x0cUserTypeEnum\x12\x10\n\x0cUNKNOWN_USER\x10\x00\x12\x16\n\x12USER_ADMINISTRATOR\x10\x01\x12\x10\n\x0cUSER_TEACHER\x10\x03\x12\x0f\n\x0bUser_OTHERS\x10\x04\x62\x06proto3'
)

_USERTYPEENUM = _descriptor.EnumDescriptor(
  name='UserTypeEnum',
  full_name='UserTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_USER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_ADMINISTRATOR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_TEACHER', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='User_OTHERS', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=22,
  serialized_end=113,
)
_sym_db.RegisterEnumDescriptor(_USERTYPEENUM)

UserTypeEnum = enum_type_wrapper.EnumTypeWrapper(_USERTYPEENUM)
UNKNOWN_USER = 0
USER_ADMINISTRATOR = 1
USER_TEACHER = 3
User_OTHERS = 4


DESCRIPTOR.enum_types_by_name['UserTypeEnum'] = _USERTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
